spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/v33tools?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=640822
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
server.servlet.context-path=/v33tools
server.port=8080

jwt.secret=YourSuperSecretKeyThatIsAtLeast32CharactersLong123456
jwt.expiration=3600000

# spring.jpa.hibernate.ddl-auto=update
# # This uses the environment variables we set in the Render dashboard
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # Keep this at 8080 to match Render's default
# server.port=8080

# Optional: Remove the context path if you want your API to be at the root (e.g., /api/login instead of /v33tools/api/login)
# server.servlet.context-path=/v33tools